datafolder: '/home/reynaudsarah/Documents/Data/simulation'

n_times: 512
n_sources: 1284 
n_electrodes: 90

#head model 
subject_name: 'fsaverage'
orientation: 'constrained'
electrode_montage: 'standard_1020'
source_sampling: 'ico3'

# simulation
# simu_name: '_dl_ses_fsaverage_st1020_'
simu_name: '_dl_ses_fsaverage_st1020_'
snr_db: 5
noise_type: {"white":1.}
replace_root: True

to_load: 10000