datafolder: '/home/triet/Documents/DATA'

n_times: 256
n_sources: 1284 
n_electrodes: 90

#head model 
subject_name: 'fsaverage'
orientation: 'constrained'
electrode_montage: 'standard_1020'
source_sampling: 'ico3'

# simulation
simu_name: ses_125ms_test
# simu_name: _dl_ses_fsaverage_st1020_visu_
snr_db: 5
noise_type: {"white":1.}
scaler_type: 'linear'
replace_root: True

to_load: 2000
