1dcnn: 
  model: 
  # _target_: contrib.eeg.models_directinv.CNN1Dpl
    channels: [90, 4096, 1284, ]
    kernel_size: 5
    bias: False
    optimizer: 
      _target_: torch.optim.Adam 
      _partial_: true
      lr : 0.001  
    criterion:
      _target_: nn.MSELoss
  # path: /home/reynaudsarah/Documents/Results/_dl_ses_fsaverage_st1020_ico3_/trained_models/no_dropout
  path: ./trained_models/baselines_retrained/_dl_ses_fsaverage_st1020_ico3_
  name: simu_sereega_srcspace_ico3_model_1dcnn_trainset_8000_epochs_300.pt

lstm:
  model:
  # _target_: contrib.eeg.models_directinv.HeckerLSTMpl 
    n_electrodes: 90
    hidden_size: 85
    n_sources: 1284
    bias: False 
    optimizer: 
      _target_: torch.optim.Adam 
      _partial_: true
      lr : 0.001  
    criterion:
      _target_: nn.MSELoss 
    mc_dropout_rate: 0
  path: ./trained_models/baselines_retrained/_dl_ses_fsaverage_st1020_ico3_
  name: simu_sereega_srcspace_ico3_model_lstm_trainset_8000_epochs_300.pt

# deepsif: 
#   model: 
#   # _target_: contrib.eeg.models_directinv.DeepSIFpl
#     num_sensor: 90
#     num_source: 1284
#     temporal_input_size: 500
#     optimizer: 
#       _target_: torch.optim.Adam
#       _partial_: true 
#       lr: 0.001 
#     criterion: 
#       _target_: torch.nn.MSELoss()
#     rnn_layer: 1
#   path: ./trained_models/baselines/ses_fsaverage_st1020_ico3
#   name: srcspace_ico3_snr_10_model_deep_sif_trainset_8000_epochs_100.pt